# Generated by Django 3.2.8 on 2021-10-17 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Planets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planet_name', models.CharField(max_length=200)),
                ('planet_coordinates', models.CharField(max_length=200)),
                ('planet_chat', models.TextField()),
                ('planet_landscape', models.TextField()),
                ('planet_players', models.TextField()),
                ('planet_collisions', models.TextField()),
                ('planet_owner', models.CharField(max_length=200)),
                ('taxation', models.CharField(max_length=150)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=500)),
                ('inventory', models.TextField()),
                ('space', models.CharField(max_length=200)),
                ('quadrant', models.TextField()),
                ('planet', models.CharField(max_length=200)),
                ('balance', models.TextField()),
                ('online', models.CharField(max_length=200)),
                ('owned_planets', models.TextField()),
            ],
        ),
    ]
